package migration

import (
	"bytes"
	"context"
	"flag"
	"fmt"
	"io/ioutil"
	"path/filepath"
	"regexp"
	"strconv"
	"testing"
	"time"
	"unicode"

	oldcapiexpv1alpha3 "github.com/giantswarm/apiextensions/v5/pkg/apis/capiexp/v1alpha3"
	oldcapzexpv1alpha3 "github.com/giantswarm/apiextensions/v5/pkg/apis/capzexp/v1alpha3"
	"github.com/giantswarm/microerror"
	"github.com/giantswarm/micrologger/microloggertest"
	"github.com/google/go-cmp/cmp"
	"k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	capzexp "sigs.k8s.io/cluster-api-provider-azure/exp/api/v1beta1"
	capiexp "sigs.k8s.io/cluster-api/exp/api/v1beta1"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
	"sigs.k8s.io/yaml"
)

var update = flag.Bool("update", false, "update .golden reference files")

func loadCR(fName string) (client.Object, error) {
	var err error
	var obj client.Object

	var bs []byte
	{
		bs, err = ioutil.ReadFile(filepath.Join("testdata", fName))
		if err != nil {
			return nil, microerror.Mask(err)
		}
	}

	// First parse kind.
	t := &metav1.TypeMeta{}
	err = yaml.Unmarshal(bs, t)
	if err != nil {
		return nil, microerror.Mask(err)
	}

	switch t.Kind {
	case "MachinePool":
		obj = new(oldcapiexpv1alpha3.MachinePool)
	case "AzureMachinePool":
		obj = new(oldcapzexpv1alpha3.AzureMachinePool)
	default:
		return nil, microerror.Maskf(unknownKindError, "kind: %s", t.Kind)
	}

	// ...and unmarshal the whole object.
	err = yaml.Unmarshal(bs, obj)
	if err != nil {
		return nil, microerror.Mask(err)
	}

	return obj, nil
}

func newFakeClient() client.Client {
	scheme := runtime.NewScheme()

	// Upstream CAPI schema
	err := capiexp.AddToScheme(scheme)
	if err != nil {
		panic(err)
	}

	// Upstream CAPZ schema
	err = capzexp.AddToScheme(scheme)
	if err != nil {
		panic(err)
	}

	// Old experimental CAPI schema
	err = oldcapiexpv1alpha3.AddToScheme(scheme)
	if err != nil {
		panic(err)
	}

	// Old experimental CAPZ schema
	err = oldcapzexpv1alpha3.AddToScheme(scheme)
	if err != nil {
		panic(err)
	}

	return fake.NewFakeClientWithScheme(scheme)
}

// normalizeFileName converts all non-digit, non-letter runes in input string to
// dash ('-'). Coalesces multiple dashes into one.
func normalizeFileName(s string) string {
	var result []rune
	for _, r := range s {
		if unicode.IsDigit(r) || unicode.IsLetter(r) {
			result = append(result, r)
		} else {
			l := len(result)
			if l > 0 && result[l-1] != '-' {
				result = append(result, rune('-'))
			}
		}
	}
	return string(result)
}

func verifyCR(t *testing.T, client client.Client, testName string, obj client.Object, nsName types.NamespacedName) {
	t.Helper()

	err := client.Get(context.Background(), nsName, obj)
	if err != nil {
		t.Fatalf("err = %#q, want %#v", microerror.JSON(err), nil)
	}

	ta, err := meta.TypeAccessor(obj)
	if err != nil {
		t.Fatalf("err = %#q, want %#v", microerror.JSON(err), nil)
	}

	out, err := yaml.Marshal(obj)
	if err != nil {
		t.Fatalf("err = %#q, want %#v", microerror.JSON(err), nil)
	}

	p := filepath.Join("testdata", fmt.Sprintf("%s_%s.golden", normalizeFileName(testName), ta.GetKind()))

	if *update {
		err = ioutil.WriteFile(p, out, 0644) // nolint:gosec
		if err != nil {
			t.Fatalf("err = %#q, want %#v", microerror.JSON(err), nil)
		}
	}

	goldenFile, err := ioutil.ReadFile(p)
	if err != nil {
		t.Fatalf("err = %#q, want %#v", microerror.JSON(err), nil)
	}

	//
	// XXX: Workaround to exclude timestamp differences from comparison.
	//
	re := regexp.MustCompile(`lastTransitionTime: "\d+-\d+-\d+T\d+:\d+:\d+Z"`)
	timeNow := time.Now()
	goldenFile = re.ReplaceAll(goldenFile, []byte(fmt.Sprintf(`lastTransitionTime: "%s"`, timeNow)))
	out = re.ReplaceAll(out, []byte(fmt.Sprintf(`lastTransitionTime: "%s"`, timeNow)))

	// Final comparison of golden version vs. one generated by test.
	if !bytes.Equal(out, goldenFile) {
		t.Fatalf("\n\n%s\n", cmp.Diff(string(goldenFile), string(out)))
	}
}

func TestEnsureCreatedIsIdempotent(t *testing.T) {
	testCases := []struct {
		name                    string
		oldMachinePoolFile      string
		oldAzureMachinePoolFile string
	}{
		{
			name:                    "case 0: Simple MachinePool",
			oldMachinePoolFile:      "old_machinepool.yaml",
			oldAzureMachinePoolFile: "old_azuremachinepool.yaml",
		},
	}

	for i, tc := range testCases {
		t.Run(strconv.Itoa(i), func(t *testing.T) {
			t.Log(tc.name)

			fakeClient := newFakeClient()
			ctx := context.Background()

			// Get old exp MachinePool from test file, this is the CR that the
			// handler is reconciling.
			o, err := loadCR(tc.oldMachinePoolFile)
			if err != nil {
				t.Fatal(err)
			}
			oldExpMachinePool, ok := o.(*oldcapiexpv1alpha3.MachinePool)
			if !ok {
				t.Fatalf("couldn't cast object %T to %T", o, oldExpMachinePool)
			}

			// Get old exp AzureMachinePool from test file, this CR should exist in etcd.
			o, err = loadCR(tc.oldAzureMachinePoolFile)
			if err != nil {
				t.Fatal(err)
			}
			oldExpAzureMachinePool, ok := o.(*oldcapzexpv1alpha3.AzureMachinePool)
			if !ok {
				t.Fatalf("couldn't cast object %T to %T", o, oldExpMachinePool)
			}
			err = fakeClient.Create(ctx, oldExpAzureMachinePool)
			if err != nil {
				t.Fatal(err)
			}

			var resource *Resource
			{
				c := Config{
					CtrlClient: fakeClient,
					Logger:     microloggertest.New(),
				}
				resource, err = New(c)
				if err != nil {
					t.Fatal(err)
				}
			}

			// Run MachinePool migration
			err = resource.EnsureCreated(ctx, oldExpMachinePool)
			if err != nil {
				t.Fatal(err)
			}

			// Run MachinePool migration
			err = resource.EnsureCreated(ctx, oldExpMachinePool)
			if err != nil {
				t.Fatal(err)
			}
		})
	}
}
