exclude: 'vendor'
fail_fast: true
repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.0.1
    hooks:
      - id: no-commit-to-branch
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.3.5
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-build
      - id: go-unit-tests
      - id: golangci-lint
