exclude: 'vendor'
fail_fast: true
repos:
- repo: git://github.com/dnephin/pre-commit-golang
  rev: v0.3.5
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-imports
    - id: golangci-lint
    - id: go-unit-tests
    - id: go-build
