apiVersion: "giantswarm.io/v1"
kind: AzureCluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  cluster:
    cluster:
      id: "${CLUSTER_NAME}"

    customer:
      id: "example-customer"

    docker:
      imageNamespace: "giantswarm"

    etcd:
      domain: "etcd.${CLUSTER_NAME}.${COMMON_DOMAIN}"
      prefix: "${CLUSTER_NAME}"
      port: 2379

    calico:
      subnet: "192.168.0.0"
      cidr: 24
      mtu: 1500

    kubernetes:
      api:
        domain: "api.${CLUSTER_NAME}.${COMMON_DOMAIN}"
        insecurePort: 8080
        ip: "172.31.0.1"
        securePort: 443
        clusterIPRange: "172.31.0.0/24"
      dns:
        ip: "172.31.0.10"
      domain: "cluster.local"
      hyperkube:
        docker:
          image: "quay.io/giantswarm/hyperkube:v1.7.5_coreos.0"
      ingressController:
        docker:
          image: "quay.io/giantswarm/nginx-ingress-controller:0.9.0-beta.11"
        insecurePort: 30010
        securePort: 30011
        domain: "api.${CLUSTER_NAME}.${COMMON_DOMAIN_INGRESS}"
        wildcardDomain: "*.${CLUSTER_NAME}.${COMMON_DOMAIN_INGRESS}"
      kubelet:
        port: 10250
      networkSetup:
        docker:
          image: "giantswarm/k8s-setup-network-environment:ba2b57155d859a1fc5d378c2a09a77d7c2c755ed"

    masters:
    - hostname: "master-1"

    workers:
    - hostname: "worker-1"

  azure:
    keyVault:
      name: "${CLUSTER_NAME}-vault"
    location: "${AZURE_LOCATION}"
    masters:
    - vmSize: "${AZURE_INSTANCE_TYPE_MASTER}"
      dataDiskSizeGB: 50
      adminUsername: "core"
      adminSSHKeyData: "${ID_RSA_PUB}"
      osImage:
        publisher: "CoreOS"
        offer: "CoreOS"
        sku: "Stable"
        version: "1465.7.0"
    workers:
    - vmSize: "${AZURE_INSTANCE_TYPE_WORKER}"
      dataDiskSizeGB: 50
      adminUsername: "core"
      adminSSHKeyData: "${ID_RSA_PUB}"
      osImage:
        publisher: "CoreOS"
        offer: "CoreOS"
        sku: "Stable"
        version: "1465.7.0"
    - vmSize: "${AZURE_INSTANCE_TYPE_WORKER}"
      dataDiskSizeGB: 50
      adminUsername: "core"
      adminSSHKeyData: "${ID_RSA_PUB}"
      osImage:
        publisher: "CoreOS"
        offer: "CoreOS"
        sku: "Stable"
        version: "1465.7.0"
    storage:
      accountType: "Standard_LRS"
    virtualNetwork:
      cidr: "10.0.0.0/16"
      masterSubnetCidr: "10.0.1.0/24"
      workerSubnetCidr: "10.0.2.0/24"
      loadBalancer:
        etcdCidr: "10.0.3.128/25"
    dnsZones:
      api:     "${COMMON_DOMAIN}"
      etcd:    "${COMMON_DOMAIN}"
      ingress: "${COMMON_DOMAIN_INGRESS}"
