apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-operator-configmap
data:
  config.yml: |
    service:
      azure:
        clientid: "${AZURE_CLIENT_ID}"
        clientsecret: "${AZURE_CLIENT_SECRET}"
        subscriptionid: "${AZURE_SUBSCRIPTION_ID}"
        tenantid: "${AZURE_TENANT_ID}"
        template:
          uri:
            version: "${AZURE_TEMPLATE_URI_VERSION}"
      kubernetes:
        incluster: true
    server:
      listen:
        address: 'http://0.0.0.0:8000'
