apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: azure-operator-local
  labels:
    app: azure-operator-local
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: azure-operator-local
    spec:
      volumes:
      - name: azure-operator-configmap
        configMap:
          name: azure-operator-configmap
          items:
          - key: config.yml
            path: config.yml
      containers:
      - name: azure-operator
        image: quay.io/giantswarm/azure-operator:local-dev
        volumeMounts:
        - name: azure-operator-configmap
          mountPath: /var/run/azure-operator/configmap/
        ports:
        - name: http
          containerPort: 8000
        args:
        - daemon
        - --config.dirs=/var/run/azure-operator/configmap/
        - --config.files=config
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 250m
            memory: 250Mi
