apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        releaseRevision: {{ .Release.Revision | quote }}
      labels:
        {{- include "labels.selector" . | nindent 8 }}
    spec:
      volumes:
      - name: {{ include "resource.default.name"  . }}-configmap
        configMap:
          name: {{ include "resource.default.name"  . }}
          items:
          - key: config.yaml
            path: config.yaml
      - name: {{ include "resource.default.name"  . }}-secret
        secret:
          secretName: {{ include "resource.default.name"  . }}
          items:
          - key: azure-secret.yaml
            path: azure-secret.yaml
          - key: dockerhub-secret.yaml
            path: dockerhub-secret.yaml
      - name: certs
        hostPath:
          path: /etc/ssl/certs/ca-certificates.crt
      serviceAccountName: {{ include "resource.default.name"  . }}
      securityContext:
        runAsUser: {{ .Values.pod.user.id }}
        runAsGroup: {{ .Values.pod.group.id }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.registry.domain }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        volumeMounts:
        - name: {{ include "resource.default.name"  . }}-configmap
          mountPath: /var/run/{{ .Chart.Name }}/configmap/
        - name: {{ include "resource.default.name"  . }}-secret
          mountPath: /var/run/{{ .Chart.Name }}/secret/
          readOnly: true
        - name: certs
          mountPath: /etc/ssl/certs/ca-certificates.crt
          readOnly: true
        {{- if .Values.ports.ingress }}
        ports:
        {{- range .Values.ports.ingress }}
        - name: {{ .name }}
          containerPort: {{ .port }}
          protocol: {{ .protocol }}
        {{- end }}
        {{- end }}
        args:
        - daemon
        - --config.dirs=/var/run/{{ .Chart.Name }}/configmap/
        - --config.dirs=/var/run/{{ .Chart.Name }}/secret/
        - --config.files=config
        - --config.files=azure-secret,dockerhub-secret
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 15
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 250m
            memory: 250Mi
          limits:
            cpu: 250m
            memory: 250Mi
