apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "resource.default.name"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - cluster.x-k8s.io
      - infrastructure.cluster.x-k8s.io
    resources:
      - clusters
      - clusters/status
      - azureclusters
      - azureclusters/status
      - azuremachines
      - azuremachines/status
      - azureclusteridentities
    verbs:
      - "*"
  - apiGroups:
      - core.giantswarm.io
    resources:
      - azureclusterconfigs
      - drainerconfigs
      - sparks
      - sparks/status
    verbs:
      - "*"
  - apiGroups:
      - provider.giantswarm.io
    resources:
      - azureconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - provider.giantswarm.io
    resources:
      - azureconfigs/status
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - release.giantswarm.io
    resources:
      - releases
    verbs:
      - get
      - list
  # The operator uses a distributed locking mechanism called kubelock https://github.com/giantswarm/kubelock.
  # It operates based on namespaces in order to achieve a distributed locking mechanism.
  # The locking is used for IPAM subnet allocation.
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - create
      - delete
      - update
  # The operator needs access to the provider agnostic CAPI CRDs.
  - apiGroups:
      - exp.cluster.x-k8s.io
    resources:
      - machinepools
      - machinepools/status
    verbs:
      - "*"
  # The operator needs read and write access to all provider specific
  # infrastructure CRs we manage for Tenant Clusters.
  - apiGroups:
      - exp.infrastructure.cluster.x-k8s.io
    resources:
      - azuremachinepools
      - azuremachinepools/status
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - endpoints
      - services
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - update
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - {{ include "resource.default.name"  . }}
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
  - nonResourceURLs:
      - "/"
      - "/healthz"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "resource.default.name"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "resource.default.name"  . }}
    namespace: {{ include "resource.default.namespace"  . }}
roleRef:
  kind: ClusterRole
  name: {{ include "resource.default.name"  . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "resource.psp.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - {{ include "resource.psp.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "resource.psp.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "resource.default.name"  . }}
    namespace: {{ include "resource.default.namespace"  . }}
roleRef:
  kind: ClusterRole
  name: {{ include "resource.psp.name" . }}
  apiGroup: rbac.authorization.k8s.io
