apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  labels:
    {{- include "azure-operator.labels" . | nindent 4 }}
data:
  secret.yaml: {{ .Values.Installation.V1.Secret.AzureOperator.SecretYaml | b64enc | quote }}
