apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
stringData:
  azure-secret.yaml: |
    service:
      azure:
        clientid: {{ .Values.azureOperatorSecret.service.azure.clientid | quote }}
        clientsecret: {{ .Values.azureOperatorSecret.service.azure.clientsecret | quote }}
        sptenantid: {{ .Values.azureOperatorSecret.service.azure.sptenantid | quote }}
        subscriptionid: {{ .Values.azureOperatorSecret.service.azure.subscriptionid | quote }}
        tenantid: {{ .Values.azureOperatorSecret.service.azure.tenantid | quote }}
  dockerhub-secret.yaml: |
    service:
      registry:
        dockerhubToken: {{ .Values.registry.dockerhub.token | quote }}
