apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "false"
spec:
  type: NodePort
  ports:
  - port: 8000
  selector:
    {{- include "labels.selector" . | nindent 4 }}
