apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
    giantswarm.io/monitoring: "true"
  annotations:
    prometheus.io/scrape: "false"
spec:
  type: NodePort
  ports:
  - port: 8000
  selector:
    {{- include "labels.selector" . | nindent 4 }}
