apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-operator-configmap
  namespace: giantswarm
data:
  config.yaml: |
    server:
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      azure:
        cloud: '{{ .Values.Installation.V1.Provider.Azure.Cloud }}'
        hostCluster:
          cidr: '{{ .Values.Installation.V1.Provider.Azure.HostCluster.CIDR }}'
          resourceGroup: '{{ .Values.Installation.V1.Provider.Azure.HostCluster.ResourceGroup }}'
          virtualNetwork: '{{ .Values.Installation.V1.Provider.Azure.HostCluster.VirtualNetwork }}'
        location: '{{ .Values.Installation.V1.Provider.Azure.Location }}'
        msi:
          enabled: '{{ .Values.Installation.V1.Provider.Azure.MSI.Enabled }}'
      installation:
        name: '{{ .Values.Installation.V1.Name }}'
      kubernetes:
        incluster: true
