apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: credential-default
  namespace: giantswarm
  labels:
    app: credentiald
    giantswarm.io/managed-by: credentiald
    giantswarm.io/organization: giantswarm
    giantswarm.io/service-type: system
data:
  azure.azureoperator.clientid: {{ .Values.Installation.V1.Secret.AzureOperator.CredentialDefault.clientid | b64enc }}
  azure.azureoperator.clientsecret: {{ .Values.Installation.V1.Secret.AzureOperator.CredentialDefault.clientsecret | b64enc }}
  azure.azureoperator.subscriptionid: {{ .Values.Installation.V1.Secret.AzureOperator.CredentialDefault.subscriptionid | b64enc }}
  azure.azureoperator.tenantid: {{ .Values.Installation.V1.Secret.AzureOperator.CredentialDefault.tenantid | b64enc }}
