apiVersion: v1
kind: Secret
type: Opaque
labels:
  app: credentiald
  giantswarm.io/managed-by: credentiald
  giantswarm.io/organization: giantswarm
  giantswarm.io/service-type: system
metadata:
  name: credential-default
  namespace: giantswarm
data:
  azure.azureoperator.clientid: {{ .Values.Installation.V1.Secret.AzureOperator.CredentialDefault.clientid | b64enc | quote }}
  azure.azureoperator.clientsecret: {{ .Values.Installation.V1.Secret.AzureOperator.CredentialDefault.clientsecret | b64enc | quote }}
  azure.azureoperator.subscriptionid: {{ .Values.Installation.V1.Secret.AzureOperator.CredentialDefault.subscriptionid | b64enc | quote }}
  azure.azureoperator.tenantid: {{ .Values.Installation.V1.Secret.AzureOperator.CredentialDefault.tenantid | b64enc | quote}}
