apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: azure-operator-psp
spec:
  privileged: false
  fsGroup:
    rule: MustRunAs
    range:
      - min: 1
        max: 65535
  runAsUser:
    rule: MustRunAsNonRoot
  runAsGroup:
    rule: MustRunAs
    range:
      - min: 1
        max: 65525
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - 'secret'
    - 'configMap'
    - 'hostPath'
  allowPrivilegeEscalation: false
  hostNetwork: false
  hostIPC: false
  hostPID: false
