apiVersion: v1
kind: Service
metadata:
  name: azure-operator
  namespace: giantswarm
  labels:
    app: azure-operator
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: NodePort
  ports:
  - port: 8000
  selector:
    app: azure-operator
