project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
image:
  name: "giantswarm/azure-operator"
  tag: "[[ .Version ]]"

pod:
  user:
    id: 1000
  group:
    id: 1000
ports:
  ingress:
    - name: "http"
      port: 8000
      protocol: "TCP"

azure:
  environmentName: ""
  managementCluster:
    cidr: ""
    resourceGroup: ""
    virtualNetwork: ""
    virtualNetworkGateway: ""
  location: ""
  msi:
    enabled: true
azureOperatorSecret:
  service:
    azure:
      clientid: ""
      clientsecret: ""
      sptenantid: ""
      subscriptionid: ""
      tenantid: ""
cluster:
  baseDomain: ""
  cni:
    mask: ""
    subnet: ""
  docker:
    daemon:
      cidr: ""
  kubernetes:
    ingressController:
      baseDomain: ""
    ssh:
      userList: ""
installation: ""
workloadCluster:
  ipam:
    network:
      cidr: ""
      subnetMaskBits: ""
  oidc:
    clientID: ""
    groupsClaim: ""
    issuerURL: ""
    usernameClaim: ""
  name: ""
  ssh:
    ssoPublicKey: ""
