project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
image:
  name: "giantswarm/azure-operator"
  tag: "[[ .Version ]]"
Installation:
  Provider:
    Azure:
      Location: westeurope
      MSI:
        Enabled: true
    Registry:
      Domain: quay.io
pod:
  user:
    id: 1000
  group:
    id: 1000
ports:
  ingress:
    - name: "http"
      port: 8000
      protocol: "TCP"
