apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-operator-configmap
data:
  config.yml: |
    service:
      azure:
        clientid: "{{.Values.azure.clientId}}"
        clientsecret: "{{.Values.azure.clientSecret}}"
        subscriptionid: "{{.Values.azure.subscriptionId}}"
        tenantid: "{{.Values.azure.tenantId}}"
        template:
          uri:
            version: "{{.Values.azure.templateUriVersion}}"
      kubernetes:
        incluster: true
    server:
      listen:
        address: 'http://0.0.0.0:8000'
