apiVersion: "giantswarm.io/v1"
kind: AzureCluster
metadata:
  name: example-cluster
spec:
  cluster:
    cluster:
      id: "example-cluster"

    customer:
      id: "example-customer"

    docker:
      imageNamespace: "giantswarm"

    etcd:
      domain: "etcd.example.azure.giantswarm.io"
      prefix: "example-cluster"
      port: 2379

    calico:
      subnet: "192.168.0.0"
      cidr: 24
      mtu: 1500

    kubernetes:
      api:
        domain: "api.example.azure.giantswarm.io"
        insecurePort: 8080
        ip: "172.31.0.1" 
        securePort: 443
        clusterIPRange: "172.31.0.0/24"
      dns:
        ip: "172.31.0.10"
      domain: "cluster.local"
      hyperkube:
        docker:
          image: "quay.io/giantswarm/hyperkube:v1.7.5_coreos.0"
      ingressController:
        docker:
          image: "quay.io/giantswarm/nginx-ingress-controller:0.9.0-beta.11"
        insecurePort: 30010
        securePort: 30011
        domain: "ingress.example.azure.gigantic.io"
        wildcardDomain: "*.example.azure.gigantic.io"
      kubelet:
        port: 10250
      networkSetup:
        docker:
          image: "giantswarm/k8s-setup-network-environment:ba2b57155d859a1fc5d378c2a09a77d7c2c755ed"

    masters:
    - hostname: "master-1"

    workers:
    - hostname: "worker-1"

  azure:
    keyVault:
      name: "example-cluster-vault"
    location: "westeurope"
    storage:
      accountType: "Standard_LRS"
    virtualNetwork:
      cidr: "10.0.0.0/16"
      masterSubnetCidr: "10.0.1.0/24"
      workerSubnetCidr: "10.0.2.0/24"      
      loadBalancer:
        apiCidr: "10.0.3.0/25"
        etcdCidr: "10.0.3.128/25"
        ingressCidr: "10.0.4.0/25"
