@startuml

state "Begin Cluster Upgrade" as beginUpgrade

[*] -> beginUpgrade

beginUpgrade : Update AzureConfig release label to 12.1.0.
beginUpgrade --> clusterUpgrade

state "Cluster Upgrade" as clusterUpgrade {
    state "Ensure CAPI & CAPZ CRs exist & match AzureConfig" as ensureCRs 

    [*] -> ensureCRs
    ensureCRs : Ensure Cluster CR
    ensureCRs : Ensure AzureCluster CR
    ensureCRs : Ensure AzureMachine CR for TC master node
    ensureCRs : Ensure cluster-user-values ConfigMap

    state "Ensure first node pool" as ensureNP

    ensureCRs --> ensureNP
    ensureNP : Ensure there is a node pool to match 1:1 built-in workers

    state NPExists <<choice>>
    ensureNP --> NPExists
    NPExists --> NPExists : Wait until all node pool workers are Ready

    state "Drain old built-in workers" as drainOldWorkers
    drainOldWorkers : Move current workload gracefully to first node pool
    NPExists --> drainOldWorkers

    state oldWorkersDrained <<choice>>
    drainOldWorkers --> oldWorkersDrained
    oldWorkersDrained --> oldWorkersDrained : Wait until all workload is moved
}

state "Cluster cleanup" as cleanup {
    oldWorkersDrained --> cleanup

    state "Delete old workers" as deleteOldWorkers
    [*] -> deleteOldWorkers
    deleteOldWorkers : Delete old built-in workers' deployment
    deleteOldWorkers : Ensure old built-in workers' VMSS is deleteOldWorkers
    deleteOldWorkers : Set AzureConfig workers field to null

}
    
 deleteOldWorkers -> [*]

@enduml
